const fs = require('fs');
let c = fs.readFileSync('src/pages/ShopPage.jsx', 'utf8');

const oldStr = ' price <= priceRange[1];\r\n    });\r\n    return next;\r\n  }, [products, sort, priceRange]);\r\n';
const newStr = ` price <= priceRange[1];\r\n    });\r\n\r\n    // Size filter\r\n    if (selectedSizes.length > 0) {\r\n      next = next.filter(p => {\r\n        const variants = p.variants?.edges?.map(e => e.node) || [];\r\n        return variants.some(v =>\r\n          v.selectedOptions?.some(o =>\r\n            o.name.toLowerCase() === 'size' &&\r\n            selectedSizes.some(s => s.toLowerCase() === o.value.toLowerCase())\r\n          )\r\n        );\r\n      });\r\n    }\r\n\r\n    // Age group filter\r\n    if (selectedAgeGroups.length > 0) {\r\n      next = next.filter(p => {\r\n        const tags = (p.tags || []).map(t => t.toLowerCase());\r\n        const title = (p.title || '').toLowerCase();\r\n        return selectedAgeGroups.some(age => {\r\n          const a = age.toLowerCase();\r\n          if (a === 'adults') return tags.some(t => ['moms','mens','womens','adults','mom','women','men','adult'].includes(t)) || !tags.some(t => ['kids','youth','toddler','baby','infant','children'].includes(t));\r\n          if (a === 'kids') return tags.some(t => ['kids','youth','children','child','kid'].includes(t)) || title.includes('kid') || title.includes('youth');\r\n          if (a === 'toddlers') return tags.some(t => ['toddler','toddlers'].includes(t)) || title.includes('toddler');\r\n          if (a === 'babies') return tags.some(t => ['baby','babies','infant','newborn'].includes(t)) || title.includes('baby') || title.includes('infant');\r\n          if (a === 'teens') return tags.some(t => ['teen','teens','teenage'].includes(t)) || title.includes('teen');\r\n          return tags.includes(a);\r\n        });\r\n      });\r\n    }\r\n\r\n    return next;\r\n  }, [products, sort, priceRange, selectedSizes, selectedAgeGroups]);\r\n`;

c = c.replace(oldStr, newStr);
fs.writeFileSync('src/pages/ShopPage.jsx', c, 'utf8');
console.log('done:', c.includes('Age group filter'));
